language: java

jdk:
    - oraclejdk8

sudo: false

script:
  - mvn clean test
  - mvn clean compile package assembly:assembly
  
deploy:
    provider: releases
    api_key: b004ea3d06c40a5dc96cf941c073d8f2ff785808
    file: /home/travis/build/AlvaroSL/Verification/target/verification.jar
    skip_cleanup: true
    on:
        repo: AlvaroSL/Verification
        tags: false
        branch: developer
        overwrite: true

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam
