language: java

jdk:
    - oraclejdk8

sudo: false

script:
  - mvn clean test
  - mvn clean compile package assembly:assembly
  
deploy:
    provider: releases
    api_key:  f5d501575052042a73e59be431b02899bc91ec25  
    file: /home/travis/build/AlvaroSL/Verification/target/verification.jar
    skip_cleanup: true
    on:
        repo: AlvaroSL/Verification
        tags: false
        branch: developer
        overwrite: true

notifications:
    - email: false  # Desactivamos las notificaciones por email para evitar spam
